### PR TITLE
Logging (In Progress)

### PR DESCRIPTION
**Pull request by asher-pembroke**
# Description

Addresses #61 

Added loggers for pysat module and instrument submodules. All submodules inherit the logging level of pysat.logger

```python
from pysat import logger, logging
from pysat import Instrument

inst = Instrument('cosmic','gps')
```
No string output for the above, unless we change the logging level:
```python
logger.setLevel(logging.DEBUG)
inst = Instrument('cosmic','gps')
```
```console
pysat INFO: pysat is searching for cosmic gps files.
pysat.instruments.cosmic_gps INFO: Building a list of COSMIC files, which can possibly take time. ~1s per 100K files
pysat.instruments.cosmic_gps INFO: Found no files, check your path or download them.
pysat INFO: Unable to find any files that match the supplied template. If you have the necessary files please check pysat settings and file locations (e.g. pysat.pysat_dir).
```

 Changed all print statements to logger.info or logger.warning statements. Have not added error logging yet. Would also like feedback on default logger level. 

## Type of change

Please delete options that are not relevant.

- New feature (non-breaking change which adds functionality)
- This change requires a documentation update - contributors should use logger syntax.

# How Has This Been Tested?

I ran all the nosetests, which passed except for the datetime errors due to module sw_f107, which is addressed elsewhere.

**Test Configuration**:
* MAC os 10.13.6
* Python 3.7.3 
* miniconda

# Checklist:

- [x] Make sure you are merging into the ``develop`` (not ``master``) branch
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] Add a note to ``CHANGELOG.md``, summarizing the changes

### CODE REVIEW

**Comment by aburrell** [comment]
I think the default level should be warning, though to mirror the current behaviour it would need to be set to info.  What do other people think?

**Comment by aburrell** [comment]
I think the `Unable to find any files that match the supplied template` should be a warning, not info.

**Comment by asher-pembroke** [comment]
Let me know if I should log all exceptions as well

**Comment by aburrell** [comment]
No, just the print statements.  Thank you for taking on this monumental task!

**Comment by asher-pembroke** [comment]
I just realized `logger.info('my','message')` produces a terrifyingly verbose logger error. The correct syntax is `logger.info('my %s', 'message')`

**Comment by rstoneback** [comment]
Looking good. There is a download error with TIMED SABER. CDAWeb may be moving things around again.

**Comment by rstoneback** [comment]
I also think the unable to find any remote files should be a warning.

logger.info('No remote files found. Unable to download latest data.')
in instrument.py .

**Comment by rstoneback** [comment]
For the default level:

For operational uses I do think warning is the appropriate level. Also probably good for those who are used to pysat.

For new users it may be a problem since there won't be any feedback.

Proposed Change:
We could change all the logging statements in init to be warnings, plus include an additional note that pysat defaults to only providing Warning level feedback with the code on how to change the level to info.

**Comment by rstoneback** [comment]
@jklenzing the change to logging will alter the output for testing. We will likely run into timeout errors unless we change the logging output during testing.

**Comment by aburrell** [comment]
I disagree, I think most of the print statements aren't particularly helpful unless you're debugging something.  Which ones in particular do you think are helpful to new users, @rstoneback?

**Comment by rstoneback** [comment]
I was thinking that new users may not realize pysat created a directory to store all of their data and they may not know anything about logging. When/if they run into trouble they may not know they have an option to get more info.

**Comment by aburrell** [comment]
Well, since the first thing you have to do with pysat is tell it where to store your data, I don't think that's a real concern.

Logging is something new users should be made aware of, but that can be done in the README and tutorial.

**Comment by rstoneback** [comment]
pysat was updated to create a data directory the first time it is run and prints out a feedback note with an example on how to set a new directory. With this pull that note will be redirected to logging.info and not seen. A logging section has been added to the docs but many people don't check out documentation. The statements in init I've brought up are only printed the first time pysat is run or the .pysat directory doesn't exist anymore for some reason.

**Comment by rstoneback** [comment]
pinging @jklenzing since I believed he authored the data directory creation changes and may want to chime in.

**Comment by jklenzing** [comment]
I think an initial ping after install is fine, but the user feedback in general needs to be cut as a default.  The travis logs are getting crazy long to scroll through, particularly on a phone.

**Comment by rstoneback** [comment]
Yes, looks like we all agree default feedback should be cut, default is warnings only, and there are only a few. I'll think about what our only default statements should be. I think we should also talk about what we really want to happen first time pysat is run on the next telecon, as in default data directories and the like.

**Comment by asher-pembroke** [comment]
@rstoneback Can I merge and close this?

**Pull request merged**
