### PR TITLE
NetCDF Export NaN metadata

### PR DESCRIPTION
**Pull request by mddepew**
# Description

Addresses issue where exported netCDF files contain unnecessary metadata. Due to the nature of the pandas, if a metadata parameter is added, it will be added to all variables. This may not always be the desired behavior. If no value is assigned to the parameter, it will be assigned nan. Thus, we can remove these parameters by not exporting metadata parameters with a value of nan. If a parameter does need to be exported with a value of nan, the name of the parameter must be added to the export_nan list that is now a part of the meta object.

Please include a summary of the change and which issue is fixed. Please also
include relevant motivation and context. List any dependencies that are required
for this change.  Please see ``CONTRIBUTING.md`` for more guidelines.

## Type of change

Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide
instructions so we can reproduce. Please also list any relevant details for
your test configuration

- Tested with COSMIC-2 GSW L2 and L1b export.

**Test Configuration**:
* Operating system Ubuntu
* Version number 18.04
* Any details about your local setup that are relevant

# Checklist:

- [X] Make sure you are merging into the ``develop`` (not ``master``) branch
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] Add a note to ``CHANGELOG.md``, summarizing the changes

### CODE REVIEW

**Comment by rstoneback** [comment]
We are going to need some form of flag to turn on or turn off the NaN metadata filter. As currently written it will filter out all the FilleValue metadata that is correctly set to NaN. Going to bring this up in the pysat meeting tomorrow.

**Comment by mddepew** [comment]
Actually in the case of fillvalue, the export_nan list includes that value by default, since it should pretty much always allow nan.

`self._export_nan = [fill_label] + export_nan`

Other values need to be included in the meta constructor with the export_nan argument.

Or they can be added or removed using the meta._export_nan list object. Eventually it might be wise to add functions to add/remove items from the list without directly accessing the object. Maybe add_to_export_nan(item) and remove_from_export_nan(item). Maybe also a get_export_nan_list() to see what's currently in the list. Somebody with more knowledge of pep-8 than myself can suggest the most pythonic way to do this. Or if you have a style guide for the project we can make it conform to that.
@rstoneback @aburrell

**Comment by rstoneback** [comment]
Somehow I completely missed you got that list in there. I looked in the wrong place for it. Thanks for the direction.

**Comment by rstoneback** [comment]
Pulling in a different reviewer since I've contributed to this code.

**Comment by rstoneback** [comment]
I actually need to tweak the tweaks I just added. Back in a bit.

**Comment by rstoneback** [comment]
This is ready for review when available @jklenzing

**Comment by rstoneback** [comment]
Thanks Jeff. I’ll make a copy for develop-3 as well.

On Jun 26, 2020, at 4:56 PM, Jeff Klenzing <notifications@github.com> wrote:

﻿

@jklenzing approved this pull request.

Looks good. I think we need these in pysat 3.0.0 as well

**Comment by rstoneback** [comment]
Tests have all passed, unsure why the integration doesn't show that.

**Pull request merged**
