### PR TITLE
ENH: added more volume units to scaling method

### PR DESCRIPTION
**Pull request by aburrell**
# Description

Added more volume units (the possible formats encountered in files are legion!) to the `scale_units` utility function.

## Type of change

Please delete options that are not relevant.

- New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Expanded unit tests.  Also:

```
import pysat

pysat.utils.scale_units('cm-3', '#/m^3')
1000000.0
```

```
pysat.utils.scale_units('#/km^3', 'km$^{-3}$')
1.0
```

**Test Configuration**:
* Operating system: OS X Big Sur
* Version number: Python 3.8
* Any details about your local setup that are relevant

# Checklist:

- [x] Make sure you are merging into the ``develop`` (not ``main``) branch
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] Add a note to ``CHANGELOG.md``, summarizing the changes

If this is a release PR, replace the first item of the above checklist with the release
checklist on the wiki: https://github.com/pysat/pysat/wiki/Checklist-for-Release

### CODE REVIEW

**Review by jklenzing — APPROVED** [review]
looks good!

**Comment by jklenzing** [comment]
I think the following lines need to be updated to accommodate the new volume units
https://github.com/pysat/pysat/blob/9777d130f57b2c08abe1ec07589add361f4448db/pysat/tests/test_utils.py#L129-L133

**Comment by jklenzing** [comment]
PEP8 alert!

**Comment by aburrell** [comment]
UGGGGGGG 🐘

**Review by jklenzing — APPROVED** [review]

**Pull request merged**
