### PR TITLE
v2.2 Release

### PR DESCRIPTION
**Pull request by rstoneback**
# Description

Version 2.2 Release.

## Type of change

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- This change includes a documentation update

# How Has This Been Tested?

Test suite ran locally and Travis CI run of test suite

# Checklist:

- [ ] Make sure you are merging into the ``develop`` (not ``master``) branch
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] Add a note to ``CHANGELOG.md``, summarizing the changes

### CODE REVIEW

**Comment by rstoneback** [comment]
First local test run:

```
======================================================================
ERROR: Checking download routine functionality for module:  icon ivm  b
----------------------------------------------------------------------
-------------------- >> begin captured logging << --------------------
pysat: WARNING: Unable to find any files that match the supplied template. If you have the necessary files please check pysat settings and file locations (e.g. pysat.pysat_dir).
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: Failure: ImportError (No module named pytest)
----------------------------------------------------------------------

ImportError: No module named pytest

----------------------------------------------------------------------
Ran 1743 tests in 1855.349s

```

The IVM-B error is expected since there is no public ICON IVM-B data yet.

I didn't have pytest since it isn't in setup.py . It only appears in test_cdaweb_methods.py .

**Comment by rstoneback** [comment]
Downloads aren't working for ROCSAT either so the tests print a warning that it was unable to download the file.

**Comment by jklenzing** [comment]
numpydoc recommends adding deprecation to the docstrings, which would make the api listing less confusing.  I can mock up a quick pr.  example:
Screen Shot 2020-07-24 at 5 32 15 PM

**Comment by jklenzing** [comment]
Other than that, the new documentation looks pretty solid

**Comment by jklenzing** [comment]
> First local test run:
> 
> 
> 
> ```
> 
> ======================================================================
> 
> ERROR: Checking download routine functionality for module:  icon ivm  b
> 
> ----------------------------------------------------------------------
> 
> -------------------- >> begin captured logging << --------------------
> 
> pysat: WARNING: Unable to find any files that match the supplied template. If you have the necessary files please check pysat settings and file locations (e.g. pysat.pysat_dir).
> 
> --------------------- >> end captured logging << ---------------------
> 
> 
> 
> ======================================================================
> 
> ERROR: Failure: ImportError (No module named pytest)
> 
> ----------------------------------------------------------------------
> 
> 
> 
> ImportError: No module named pytest
> 
> 
> 
> ----------------------------------------------------------------------
> 
> Ran 1743 tests in 1855.349s
> 
> 
> 
> ```
> 
> 
> 
> The IVM-B error is expected since there is no public ICON IVM-B data yet.
> 
> 
> 
> I didn't have pytest since it isn't in setup.py . It only appears in test_cdaweb_methods.py . 

That’s a mistake. Purest shouldn’t be here

**Comment by rstoneback** [comment]
I took a look when it failed and pytest is intrinsic to that one. I’m guessing the inclusion of the file is the mistake?

**Comment by jklenzing** [comment]
> I took a look when it failed and pytest is intrinsic to that one. I’m guessing the inclusion of the file is the mistake?

Yeah, i must have crossed the streams at some point while porting updates over.  the test in question should use the old school `@raises` to catch the error, not pytest.

**Comment by rstoneback** [comment]
Sounds like the pytest one may trip up the TravisCI testing then.  I’ll work on a restoration direct into develop but only after local test pass.

**Comment by rstoneback** [comment]
I've got a local fix in for the test to use nose. I've also brought in the deprecated thing since I'm here. I'll take a look for others while tests are running on Travis.

**Comment by jklenzing** [comment]
I've got a "last-minute patch" branch started.  Just saw your note.  I've got a few other docstring format things too.

**Comment by rstoneback** [comment]
> I've got a "last-minute patch" branch started. Just saw your note. I've got a few other docstring format things too.

Looks like we crossed streams a bit :)

I have the test working and the deprecation stuff in custom as well as over in utils. I followed the breadcrumbs in the changelog. I think if I push to develop now I can get ahead of the current scheduled test.

**Comment by rstoneback** [comment]
> > I've got a "last-minute patch" branch started. Just saw your note. I've got a few other docstring format things too.
> 
> Looks like we crossed streams a bit :)
> 
> I have the test working and the deprecation stuff in custom as well as over in utils. I followed the breadcrumbs in the changelog. I think if I push to develop now I can get ahead of the current scheduled test.

hehehe, nope. 2 minutes too late. 👎

**Comment by rstoneback** [comment]
you are way ahead on the changes :) I'll send you an email with my test code in case you haven't got there.

**Comment by jklenzing** [comment]
I did take a break for an afternoon bike ride, which I'll credit with my renewed code review skills.  :bike:

**Comment by jklenzing** [comment]
Tests are passing here.  I wonder if conda includes pytest by default, which is why we didn't see an error before?

**Comment by rstoneback** [comment]
Oh, maybe so. Well, that's nice.  I'll go and review and approve the other one, I've already looked at it. I'll be back soon.

**Comment by rstoneback** [comment]
Well, I think we technically have time to get the other pull in. This one should pass tests here shortly. 1 hour for the other pull to clear, another hour back over here for testing. All checks would be green, assuming an approval of course :)

**Comment by jklenzing** [comment]
Running some local tests here to see if things are working with my setup.  I've gone through the formatted docs, which look fine.  Just a few other checks.

**Comment by rstoneback** [comment]
hey hey, we made it!

http://outrightgeekery.com/wp-content/uploads/2014/07/firehose.gif

**Pull request merged**
