### PR TITLE
ENH/STY: Files rename + flake8 

### PR DESCRIPTION
**Pull request by jklenzing**
# Description

Addresses #336

- Renames `_files` as `files`.  The change seems relatively straightforward as far as tests go.
- Also addresses flake8 issues in files.py

## Type of change

- Breaking change (fix or feature that would cause existing functionality
      to not work as expected)

# How Has This Been Tested?

Unit tests via pytest.

# Checklist:

- [x] Make sure you are merging into the ``develop`` (not ``master``) branch
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] Add a note to ``CHANGELOG.md``, summarizing the changes

### CODE REVIEW

**Comment by jklenzing** [comment]
This change has some conflicts with #441.  recommend merging that in first, then sorting out conflicts here and opening for review.

**Comment by jklenzing** [comment]
Looking at the downstream packages, only pysatMadrigal is calling from this routine.  Prepared a branch there to use the new notation.

**Comment by jklenzing** [comment]
Actually, looking over the docs, we might want to discuss this at the next meeting.  I want to be sure the syntax approach is correct now that we have both `pysat.Files` and `pysat.files`.  converting back to draft pending further discussion

**Comment by aburrell** [comment]
Approval of changes in the code review.

**Comment by jklenzing** [comment]
Closing in favor of #505.

**Pull request closed without merging**
