### PR TITLE
RC Update with develop-3

### PR DESCRIPTION
**Pull request by aburrell**
# Description

Merging develop branch with all of the pysat 3.0.0 milestones completed into the early release candidate branch.

## Type of change

Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- This change requires a documentation update

# How Has This Been Tested?

This has been tested by running things locally and on Travis.

# Checklist:

- [N/A] Make sure you are merging into the ``develop`` (not ``main``) branch
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] Add a note to ``CHANGELOG.md``, summarizing the changes

### CODE REVIEW

**Comment by aburrell** [comment]
The commit before things got messed up by main is: https://github.com/pysat/pysat/tree/5c2fcb94989ffa51c652c16a1bd297bc29410873

**Comment by rstoneback** [comment]
Thanks for working on this @aburrell. 
 - I'm a little confused about what is what, though it looks like a merge with main didn't go as intended and you are/have (?) sorted that out.
 - Should we be merging with main or just forcing the merge by replacing main with develop-3 versions? It seems, without investigation, like develop-3 is canonical at this point. Since you have been working on it, what good stuff is in main but not develop-3? This may not be easily answered via text so I will also poke around more myself.

**Comment by aburrell** [comment]
Well, yes, develop-3 was canonical but during the merge resolution commits were made to develop-3 and that is no longer the case.  It had appeared as if any place where there were conflicts removed files was treated as a conflict, but this was not the case.  Also, there were other cases where git decided to add old code lines back in as the didn't "conflict".  So.  It would have been an option to just replace main with develop-3, but now it isn't.

Honestly, not sure how that happened because the changes were made to v3-0-rc1, but who knows!  This pull should fix things and I went through and found the point where the branches got messed up to verify against, so fingers crossed.  You and @jklenzing should both look critically at the release candidate after this is merged in .

**Comment by rstoneback** [comment]
> Well, yes, develop-3 was canonical but during the merge resolution commits were made to develop-3 and that is no longer the case. It had appeared as if any place where there were conflicts removed files was treated as a conflict, but this was not the case. Also, there were other cases where git decided to add old code lines back in as the didn't "conflict". So. It would have been an option to just replace main with develop-3, but now it isn't.
> 
> Honestly, not sure how that happened because the changes were made to v3-0-rc1, but who knows! This pull should fix things and I went through and found the point where the branches got messed up to verify against, so fingers crossed. You and @jklenzing should both look critically at the release candidate after this is merged in .

Thanks for the additional info. I tried my own path to make sure I have a good sense of the code changes and to provide a another point of reference for a critical comparison. When I started I didn't really appreciate that develop-3 already had changes but here we are :)

**Review by rstoneback — APPROVED** [review]
The only way out is forward :)

**Comment by rstoneback** [comment]
> The commit before things got messed up by main is: https://github.com/pysat/pysat/tree/5c2fcb94989ffa51c652c16a1bd297bc29410873

I converted this commit hash into a branch so we can loop it into GitHub processes, https://github.com/pysat/pysat/tree/backup_d3_pre_merge

**Pull request merged**
