### PR TITLE
ENH: cdflib interface

### PR DESCRIPTION
**Pull request by asherp**
# Description

Addresses # (issue)

attempting to replace `pysatCDF` calls in `nasa_cdaweb` with `cdflib`

## Type of change

- New feature (non-breaking change which adds functionality)
- This change requires a documentation update

# How Has This Been Tested?

Existing tests should be reproducible

**Test Configuration**:
* Operating system MacOS 
* 10.14.6
* miniconda Python 3.7.3

# Checklist:

- [ ] Make sure you are merging into the ``develop`` (not ``master``) branch
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] Add a note to ``CHANGELOG.md``, summarizing the changes

### CODE REVIEW

**Comment by asherp** [comment]
Hey @rstoneback was wondering if you can help me understand why the cnofs_plp load method fails. My test fails locally too, but I'm having trouble getting a minimum failing example to work in a notebook.

**Comment by rstoneback** [comment]
On my list but as you can see I have a delay.

**Comment by jklenzing** [comment]
Trying this branch out. Test code:
```
import pysat
import datetime as dt
date = dt.datetime(2009, 1, 1)
plp = pysat.Instrument('cnofs', 'plp')
plp.load(date=date)
plp.data.index
```
The `develop-3` branch produces:
```
DatetimeIndex([       '2009-01-01 00:00:00',        '2009-01-01 00:00:01',
                      '2009-01-01 00:00:02',        '2009-01-01 00:00:03',
                      '2009-01-01 00:00:04',        '2009-01-01 00:00:05',
               '2009-01-01 00:00:05.999000',        '2009-01-01 00:00:07',
                      '2009-01-01 00:00:08',        '2009-01-01 00:00:09',
               ...
                      '2009-01-01 23:59:50', '2009-01-01 23:59:50.999000',
                      '2009-01-01 23:59:52',        '2009-01-01 23:59:53',
                      '2009-01-01 23:59:54',        '2009-01-01 23:59:55',
               '2009-01-01 23:59:55.999000',        '2009-01-01 23:59:57',
                      '2009-01-01 23:59:58', '2009-01-01 23:59:58.999000'],
              dtype='datetime64[ns]', length=86400, freq=None)
```
as expected, whereas `cdflib` produces
```
Index([                            0,                             1,
                                   2,                             3,
                                   4,                             5,
                                   6,                             7,
                                   8,                             9,
       ...
                 2009-01-01 23:59:50, 2009-01-01 23:59:50.999000072,
                 2009-01-01 23:59:52,           2009-01-01 23:59:53,
                 2009-01-01 23:59:54,           2009-01-01 23:59:55,
       2009-01-01 23:59:55.999000072,           2009-01-01 23:59:57,
                 2009-01-01 23:59:58, 2009-01-01 23:59:58.999000072],
      dtype='object', length=172800)
```
Note the length is double.  Somehow the index is a list of integers appended by the datetime values.  For the data sets, the ints have values, the datetimes have NaNs.
```
0                                6.339799e+13
1                                6.339799e+13
2                                6.339799e+13
3                                6.339799e+13
4                                6.339799e+13
5                                6.339799e+13
6                                6.339799e+13
7                                6.339799e+13
                                     ...     
2009-01-01 23:59:52                       NaN
2009-01-01 23:59:53                       NaN
2009-01-01 23:59:54                       NaN
2009-01-01 23:59:55                       NaN
2009-01-01 23:59:55.999000072             NaN
2009-01-01 23:59:57                       NaN
2009-01-01 23:59:58                       NaN
2009-01-01 23:59:58.999000072             NaN
Name: EPOCH, Length: 172800, dtype: float64
```
Not sure where the error is coming from.

**Comment by jklenzing** [comment]
Not sure if this is the root cause of the error, but PLP uses 'EPOCH' rather than 'Epoch'.  This data is showing up as a variable when I try to load PLP using cdflib.

https://github.com/pysat/pysat/blob/69ee136638a10cdbaf19b766c0fb6c645f2ddfe0/pysat/instruments/methods/nasa_cdaweb.py#L418-L420

**Comment by jklenzing** [comment]
Update: Changing line 418 to 
`if varname.lower() != 'epoch':` 
fixes it locally for me.

**Comment by jklenzing** [comment]
Similar fix needed in the plp cleaning routine:

https://github.com/pysat/pysat/blob/69ee136638a10cdbaf19b766c0fb6c645f2ddfe0/pysat/instruments/cnofs_plp.py#L111-L114

**Comment by jklenzing** [comment]
To finish up documenting this, pysatCDF had some routines to account for different capitalization schemes for Epoch, which is why it didn't affect us before.  This might be a better way to implement rather than my quick fix above.  @rstoneback?

https://github.com/pysat/pysatCDF/blob/b2db6290c2a7c8c10700e312b7ab400a49240dca/pysatCDF/_cdf.py#L617-L623

**Comment by jklenzing** [comment]
On further testing, this resolves the epoch issue, but it still fails in the clean routine.  Here's the errors I get:
```
pysat/instruments/cnofs_plp.py:113: in clean
    idx, = np.where(inst[key] == inst.meta[key, inst.fill_label])
```
and 
```
E               ValueError: Lengths must match to compare

../../../anaconda3/lib/python3.7/site-packages/pandas/core/ops.py:1745: ValueError
```

**Comment by rstoneback** [comment]
> To finish up documenting this, pysatCDF had some routines to account for different capitalization schemes for Epoch, which is why it didn't affect us before. This might be a better way to implement rather than my quick fix above. @rstoneback?
> 
> https://github.com/pysat/pysatCDF/blob/b2db6290c2a7c8c10700e312b7ab400a49240dca/pysatCDF/_cdf.py#L617-L623

The time name being 'Epoch' is assumed by many areas of pysat. I believe I wrote that requirement down somewhere. A long time ago I thought NASA maintained a standard of Epoch on CDAWeb files. I think the time name should be checked by the load routine itself.

**Comment by rstoneback** [comment]
> OK, `inst.meta[key, inst.fill_label]` returns a single value array, hence the "Lengths must match" message. It looks like changing Line 114 to
> 
> ```
> idx, = np.where(inst[key] == inst.meta[key, inst.fill_label][0])
> ```
> 
> works properly.

Thanks for working on this @jklenzing and @asher-pembroke. Could it be this fix is required because something earlier in the processing is different?

**Comment by jklenzing** [comment]
I think we should try to fix it at the lowest level we can in case other instruments have this issue.  PLP is also using an earlier version an earlier version of CDF (3.2.4), which could be part of the problem.

**Comment by rstoneback** [comment]
> I think we should try to fix it at the lowest level we can in case other instruments have this issue. PLP is also using an earlier version an earlier version of CDF (3.2.4), which could be part of the problem.

Sure. Any reason not to include it in the new to_pysat method like the old one?

**Comment by jklenzing** [comment]
> Sure. Any reason not to include it in the new to_pysat method like the old one?

Sounds appropriate to me.

**Comment by rstoneback** [comment]
documenting a link Liam sent me on CDFLib, https://github.com/lkilcommons/pycdf2cdflib/blob/master/pycdf2cdflib.ipynb

**Comment by jklenzing** [comment]
There's been a ton of updates to the test environment since this started.  Working on merging these in to make sure the tests are passing.

**Comment by jklenzing** [comment]
Running into an error on rocsat1_ivm
```
error: unpack_from requires a buffer of at least 12 bytes
```
everything else seems to work ok.

**Comment by jklenzing** [comment]
Closing since this functionality will migrate to pysatNASA.  See pysat/pysatNASA#3

**Pull request closed without merging**
