### PR TITLE
File style update

### PR DESCRIPTION
**Pull request by aburrell**
# Description

Code scrub of Files class.  Includes:
- Adding and improving docstrings
- Changing variable names to be descriptive
- Organizing class methods by type
- Adding and clarifying block/inline comments

## Type of change

Please delete options that are not relevant.

- Style update

# How Has This Been Tested?

Running unit tests locally.

# Checklist:

- [x] Make sure you are merging into the ``develop`` (not ``main``) branch
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] Add a note to ``CHANGELOG.md``, summarizing the changes

### CODE REVIEW

**Comment by rstoneback** [comment]
Thanks @aburrell! I tried a similar improvement over in #637 so it may make sense to target that branch.

**Comment by aburrell** [comment]
@rstoneback there's a lot more going on there.  Perhaps it would make more sense to also push this branch into that draft PR after this one is merged.

**Review by jklenzing — APPROVED** [review]
Looks good.  Let's push this into the develop-3 branch now and update the draft accordingly.

**Comment by aburrell** [comment]
Coverage is up in `_files.py` so, all good.

**Pull request merged**
