### PR TITLE
Cosmic Bugs

### PR DESCRIPTION
**Pull request by rstoneback**
# Description

Addresses # (issue)

A user reported an inability to load atmPrf files as part of cosmic_gps in issue #333. I have a first draft fix to support loading. I also noticed a couple feedback bugs, which I've corrected.

## Type of change

- Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Downloaded and loaded COSMIC atmPrf files on my local machine.

The user report has a more complete listing (#333)

**Test Configuration**:
* Mac OS 10.12.6, also reproduced on newer version
* pysat 2.1

# Checklist:

- [x] Make sure you are merging into the ``develop`` (not ``master``) branch
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] Add a note to ``CHANGELOG.md``, summarizing the changes

### CODE REVIEW

**Comment by rstoneback** [comment]
Test failure related to CDAWeb download issue, not code here.

**Comment by jklenzing** [comment]
Since this is outside the Eye of Travis, I'll try to test it out tonight.  Created the twin pull for pysat 3.0.0 in #335.

**Comment by rstoneback** [comment]
Thanks Jeff!!

**Comment by jklenzing** [comment]
Caught a new bug here.  The file list does not update after downloads, only the first time a given data product is called.  So calling:
```
import pysat
atm = pysat.Instrument(platform='cosmic', name='gps', tag='atmPrf')      
start = pysat.datetime(2018,1,1)
stop = pysat.datetime(2018,1,2)
atm.download(start, stop, user=user, password=password)
```
successfully downloads the files assuming `atmprf` has never been called before.  `atm.files.files` has an appropriate output.

Following this with
```
start = pysat.datetime(2013, 1, 1)
stop = pysat.datetime(2013, 1, 2)
atm.download(start, stop, user=user, password=password)
```
will successfully download the new files (as confirmed in the finder window), but invoking `atm.files.files` will only show the 2018 data downloaded previously.

This is repeatable for the other data tags here.

**Comment by rstoneback** [comment]
I've tried your commands, plus alternate groupings of download commands and I have not yet run into this problem. the list_files method uses custom code, perhaps it should be rewritten to use Files class methods.

**Comment by rstoneback** [comment]
I updated the list_files method to use pysat provided methods. Hopefully this proves more robust.

As general notes, we need to make the methods in _files.py more visible. Further, the parse_delimited_filename method didn't work on COSMIC files though I think it should've. Currently using the fixed_width method instead.

**Comment by rstoneback** [comment]
Test failure related to the merge I was forced into:

======================================================================
FAIL: Checking load routine functionality for module with clean level "none":  sw f107 forecast 
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/build/pysat/pysat/pysat/tests/test_instruments.py", line 288, in check_load
    assert not inst.empty
AssertionError

**Comment by jklenzing** [comment]
Still having issues with the recent updates, but getting closer to figuring it out.  The new files are being stamped with 2018 rather than the actual year.  Running `atm.files.files` yields
```
2018-03-11 23:53:02.005430016    2011.070/atmPrf_C004.2011.070.23.53.G02_2013.3...
2018-03-11 23:53:18.010930176    2011.070/atmPrf_C005.2011.070.23.53.G18_2013.3...
2018-03-11 23:53:19.020420096    2011.070/atmPrf_C002.2011.070.23.53.G19_2013.3...
2018-03-11 23:54:03.018390016    2011.070/atmPrf_C002.2011.070.23.54.G03_2013.3...
2018-03-11 23:56:06.020169984    2011.070/atmPrf_C002.2011.070.23.56.G06_2013.3...
```
for the code above.  This also occurs for some files from other years, all get 2018 but accurate month and date.

**Comment by rstoneback** [comment]
Do you get any notes about there being duplicate files? If the same date is being assigned to more than one file than the last file is kept, the earlier ones are dropped.

**Comment by jklenzing** [comment]
OK, deleted all my cosmic files and the records under `.pysat`.  The issue with the bad year is gone.  I suspect it was fixed with the new updates, and I was dealing with a bad list from a prior version.

**Comment by jklenzing** [comment]
The bad news is I am now getting this:
```
In [12]: atm.load(date=start)                                                                                                         
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-12-8be95bf291c7> in <module>
----> 1 atm.load(date=start)

~/code/pysat/pysat/_instrument.py in load(self, yr, doy, date, fname, fid, verifyPad)
   1370         # if self.pad is False, load single day
   1371         else:
-> 1372             self.data, meta = self._load_data(date=self.date, fid=self._fid)
   1373             if not self.empty:
   1374                 self.meta = meta

~/code/pysat/pysat/_instrument.py in _load_data(self, date, fid)
   1052             try:
   1053                 data, mdata = self._load_rtn(load_fname, tag=self.tag,
-> 1054                                              sat_id=self.sat_id, **self.kwargs)
   1055                 # ensure units and name are named consistently in new Meta
   1056                 # object as specified by user upon Instrument instantiation

~/code/pysat/pysat/instruments/cosmic_gps.py in load(fnames, tag, sat_id)
    163         # call separate load_files routine, segemented for possible
    164         # multiprocessor load, not included and only benefits about 20%
--> 165         output = pysat.DataFrame(load_files(fnames, tag=tag, sat_id=sat_id))
    166         utsec = output.hour * 3600. + output.minute * 60. + output.second
    167         output.index = \

~/code/pysat/pysat/instruments/cosmic_gps.py in load_files(files, tag, sat_id, altitude_bin)
    340     main_frame = pysat.DataFrame(main_dict)
    341     # get indices needed to parse data
--> 342     lengths = main_dict_len[main_dict.keys()[0]]
    343     # get largest length and create numpy array with it
    344     # used to speed up reindexing below

TypeError: 'dict_keys' object is not subscriptable
```

**Comment by jklenzing** [comment]
I think this may be a python 3 thing.  Getting the same for:
```
In [13]: main_dict = {'a': 1, 'b': 2}                                                                                                 

In [14]: main_dict                                                                                                                    
Out[14]: {'a': 1, 'b': 2}

In [15]: main_dict.keys()                                                                                                             
Out[15]: dict_keys(['a', 'b'])

In [16]: main_dict.keys()[0]                                                                                                          
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-16-c99a34dfcd40> in <module>
----> 1 main_dict.keys()[0]

TypeError: 'dict_keys' object is not subscriptable
```

**Comment by jklenzing** [comment]
Found and fixed it.  Needs to be converted to a list first.

https://stackoverflow.com/questions/17322668/typeerror-dict-keys-object-does-not-support-indexing

This works for the 2011 file. Still running into issues with the 2018 file.  Will document later.

**Comment by jklenzing** [comment]
Feedback from 2018 file.  Note this is a different solution set on CDAAC from the 2011 file in the original issue.

```
In [6]: start = pysat.datetime(2018, 1, 1)                                                                                            

In [7]: atm.load(date=start)                                                                                                          
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-7-8be95bf291c7> in <module>
----> 1 atm.load(date=start)

~/code/pysat/pysat/_instrument.py in load(self, yr, doy, date, fname, fid, verifyPad)
   1370         # if self.pad is False, load single day
   1371         else:
-> 1372             self.data, meta = self._load_data(date=self.date, fid=self._fid)
   1373             if not self.empty:
   1374                 self.meta = meta

~/code/pysat/pysat/_instrument.py in _load_data(self, date, fid)
   1052             try:
   1053                 data, mdata = self._load_rtn(load_fname, tag=self.tag,
-> 1054                                              sat_id=self.sat_id, **self.kwargs)
   1055                 # ensure units and name are named consistently in new Meta
   1056                 # object as specified by user upon Instrument instantiation

~/code/pysat/pysat/instruments/cosmic_gps.py in load(fnames, tag, sat_id)
    163         # call separate load_files routine, segemented for possible
    164         # multiprocessor load, not included and only benefits about 20%
--> 165         output = pysat.DataFrame(load_files(fnames, tag=tag, sat_id=sat_id))
    166         utsec = output.hour * 3600. + output.minute * 60. + output.second
    167         output.index = \

~/code/pysat/pysat/instruments/cosmic_gps.py in load_files(files, tag, sat_id, altitude_bin)
    338     # create a single data frame with all bits, then
    339     # break into smaller frames using views
--> 340     main_frame = pysat.DataFrame(main_dict)
    341     # get indices needed to parse data
    342     lengths = main_dict_len[list(main_dict.keys())[0]]

~/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py in __init__(self, data, index, columns, dtype, copy)
    390                                  dtype=dtype, copy=copy)
    391         elif isinstance(data, dict):
--> 392             mgr = init_dict(data, index, columns, dtype=dtype)
    393         elif isinstance(data, ma.MaskedArray):
    394             import numpy.ma.mrecords as mrecords

~/anaconda3/lib/python3.7/site-packages/pandas/core/internals/construction.py in init_dict(data, index, columns, dtype)
    210         arrays = [data[k] for k in keys]
    211 
--> 212     return arrays_to_mgr(arrays, data_names, index, columns, dtype=dtype)
    213 
    214 

~/anaconda3/lib/python3.7/site-packages/pandas/core/internals/construction.py in arrays_to_mgr(arrays, arr_names, index, columns, dtype)
     49     # figure out the index, if necessary
     50     if index is None:
---> 51         index = extract_index(arrays)
     52     else:
     53         index = ensure_index(index)

~/anaconda3/lib/python3.7/site-packages/pandas/core/internals/construction.py in extract_index(data)
    315             lengths = list(set(raw_lengths))
    316             if len(lengths) > 1:
--> 317                 raise ValueError('arrays must all be same length')
    318 
    319             if have_dicts:

ValueError: arrays must all be same length
```

**Comment by jklenzing** [comment]
> Do you get any notes about there being duplicate files? If the same date is being assigned to more than one file than the last file is kept, the earlier ones are dropped.

I didn't see any notes about that, but I don't think I would have with the unique dates chosen.

**Comment by aburrell** [comment]
> OK, deleted all my cosmic files and the records under `.pysat`. The issue with the bad year is gone. I suspect it was fixed with the new updates, and I was dealing with a bad list from a prior version.

Is this another bug?

**Comment by jklenzing** [comment]
> > OK, deleted all my cosmic files and the records under `.pysat`. The issue with the bad year is gone. I suspect it was fixed with the new updates, and I was dealing with a bad list from a prior version.
> 
> Is this another bug?

It might be.  I can poke around to see if this is something consistent with the older version of pysat for cosmic files.

It's probably worth having an option for `inst.files.files` that will trash the old list and start with whatever has been downloaded.  The files are good, it's just that if the list under `.pysat` is corrupted, the files become invisible to pysat.  I can write up an issue for this.

**Comment by rstoneback** [comment]
we have that option at instantiation, cosmic = pysat.Instrument(‘cosmic’, ‘gps’, update_files=True)

you can also issue, cosmic.files.refresh() at any time.

**Comment by jklenzing** [comment]
With regards to the 2018 file above, essentially this comes down to the 2013 reprocessed data vs the processed data, which are in two different formats.  This branch works on the reprocessed data, but not the other set, which has more variables.

Running ariables.keys() on each file yields:
2011 file =>  odict_keys(['Lat', 'Lon', 'MSL_alt', 'Ref', 'Azim', 'Pres', 'Temp', 'Bend_ang', 'Opt_bend_ang', 'Impact_height', 'Bend_ang_stdv', 'Bend_ang_conf', 'OL_par', 'OL_ipar', 'OL_vec1', 'OL_vec2', 'OL_vec3', 'OL_vec4'])
2018 file => odict_keys(['Lat', 'Lon', 'MSL_alt', 'Ref', 'Azim', 'Pres', 'Temp', 'Bend_ang1', 'Bend_ang2', 'Bend_ang', 'Impact_height', 'Bend_ang_stdv', 'Bend_ang_conf', 'ies', 'hes', 'wes', 'OL_par', 'OL_ipar', 'OL_vec1', 'OL_vec2', 'OL_vec3', 'OL_vec4'])

**Comment by jklenzing** [comment]
> we have that option at instantiation, cosmic = pysat.Instrument(‘cosmic’, ‘gps’, update_files=True) you can also issue, cosmic.files.refresh() at any time.

Thanks!  I thought I was doing it the hard way.

**Comment by jklenzing** [comment]
Found it.  There's three extra variables that should be tied to OL_par.  I can work up a fix I think.

**Comment by jklenzing** [comment]
OK, It's working on my end for both flavors of atmPrf data.  @rstoneback, do you want to give this a spin to validate?

**Comment by rstoneback** [comment]
I as able to load data from 2013, 1 and 2018, 1 for atmPrf

**Comment by rstoneback** [comment]
I checked the other products before using 2013 data. I will check again with 2018.

**Comment by rstoneback** [comment]
I checked all the file types for both 2013, 1 and 2018, 1.

**Pull request merged**
