### PR TITLE
V3 0 4rc

### PR DESCRIPTION
**Pull request by rstoneback**
# Description

New bug release. Improves compatibility with latest xarray release, while remaining backwards compatible. Fixes a bug in time generation routines that didn't handle cadences less than a second.

## Type of change

Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New release

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide
instructions so we can reproduce. Please also list any relevant details for
your test configuration

- Online CI

**Test Configuration**:
* Operating system: GitHub Actions
* Version number: Python 3.Xs
* Any details about your local setup that are relevant

# Checklist:

- [x] Update the version number
- [x] Verify and update Zenodo information in .zenodo.json
- [x] doc tests pass locally
- [x] activate this branch on readthedocs (https://pysat.readthedocs.io/en/v3-0-4rc/)
- [x] Upload the test distribution to the testPyPi server
- [x] Contacted developers and users about the future release
- [x] Performed integration tests with downstream packages (include list of these packages)
- [x] Create a wiki page with the release text (https://github.com/pysat/pysat/wiki/v3.0.4-Release-Text)
- [ ] After approval, confirm all changes from the RC pull are listed in the wiki release text.
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] Add a note to ``CHANGELOG.md``, summarizing the changes

If this is a release PR, replace the first item of the above checklist with the release
checklist on the wiki: https://github.com/pysat/pysat/wiki/Checklist-for-Release

### CODE REVIEW

**Comment by jklenzing** [comment]
I've got one more bug fix in at #1041, which affects ecosystem packages with FTP instruments.

**Comment by jklenzing** [comment]
> Where's the list of packages to test this on? Given the previous break I definitely don't want to shortchange the integration tests.

I'd also recommend running a local test against a simulated CI response as outlined in #1041. See below

> In pysat.utils._core.py, replace `(os.environ.get('CI') == 'true')` on line 470 with `(os.environ.get('CI') is None)` to simulate a True response while on a local system.

**Comment by jklenzing** [comment]
Checking locally for pysatSpaceWeather `develop`:
CI simulation: 155 passed, 16 skipped, 107 warnings in 13.79s
Normal: 170 passed, 19 skipped, 129 warnings in 20.73s

There are 3 FTP instruments that should not be added to the tests in the CI environment.  Each of these contains a test for `download`, 4 tests for `load` at different clean levels, and a test for `remote_file_list` that is nominally skipped (for instruments without this method).  Since these are all added via a longer list to parametrize, we expect to see a reduction of 15 passed tests and 3 skipped tests rather than an increase in skipped tests.

**Comment by aburrell** [comment]
> I'd also recommend running a local test against a simulated CI response as outlined in https://github.com/pysat/pysat/pull/1041

Should this be added to the RC or the standard PR checklist?

**Comment by jklenzing** [comment]
> > I'd also recommend running a local test against a simulated CI response as outlined in #1041
> 
> Should this be added to the RC or the standard PR checklist?

Probably. I've opened #1042 for long term discussion.  It would prevent the issue we ran into with pysatSpaceWeather.

**Comment by jklenzing** [comment]
- [ ] pysatCDAAC
- [ ] pysatCDF
- [ ] pysatMadrigal
- [x] pysatMissions
- [ ] pysatModels
- [x] pysatNASA
- [ ] pysatSeasons
- [x] pysatSpaceWeather
- [x] pysatSpaceWeather (w/ CI sim)

**Review by jklenzing — APPROVED** [review]
Approved pending checks in the other packages.

**Comment by rstoneback** [comment]
I'm allowing myself one more run on OMMBV to see if I can fill in a few more areas at high lat. My computer should be free enough tomorrow to run local tests against pysat.

**Review by aburrell — APPROVED** [review]

**Pull request merged**
