### PR TITLE
Vectorize meta functions

### PR DESCRIPTION
**Pull request by rstoneback**
# Description

Addresses #767

Vectorizes `var_case_name` and updates functions calls where relevant to make use of the new feature. The 'bug' here is how many function calls a made when metadata is set.

Vectorizes `Meta.attr_case_name`, `_insert_default_values`, and modifies the appropriate function calls. Reduces the number of function calls required.

Note: I also tried vectorizing `__contains__`, and that worked, but `blah in something` doesn't. I was pushing python into places it didn't want to go.

Note: Also includes a bit of cleanup within `__setitem__` and `__getitem__`

Initially started as two pulls to help ensure I didn't make another sprawling pull. Condensing together for ease of review since a sprawl no longer seems likely.

## Type of change

Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide
instructions so we can reproduce. Please also list any relevant details for
your test configuration

- Ran the unit test suite.
- Added a test for list of str input

**Test Configuration**:
* Operating system: MacOS 11.5
* Version number: Python 3.8
* Any details about your local setup that are relevant

# Checklist:

- [x] Make sure you are merging into the ``develop`` (not ``main``) branch
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] Add a note to ``CHANGELOG.md``, summarizing the changes

If this is a release PR, replace the first item of the above checklist with the release
checklist on the wiki: https://github.com/pysat/pysat/wiki/Checklist-for-Release

### CODE REVIEW

**Comment by rstoneback** [comment]
> So... that was my review from a few days ago. Looks like my internet decided to betray me 🦈

Thanks for the review, delayed or not!

```
It's not a big truck. It's a series of tubes. And if you don't understand, those tubes can be filled and
 if they are filled, when you put your message in, it gets in line and it's going to be delayed by anyone
 that puts into that tube enormous amounts of material, enormous amounts of material.
```
[Ted Stevens](https://en.wikipedia.org/wiki/Series_of_tubes) was right all along! 🙈

**Comment by rstoneback** [comment]
I'm getting a weird error for one of the tests, `TestFileDirectoryTranslations`. Breaking on sw, f107, historic. I haven't touched code in the area so 🤷 at the moment.

**Comment by aburrell** [comment]
Is it still breaking for you on historic F10.7 data?  It worked for me, so would appreciate some example code to test.

**Comment by rstoneback** [comment]
Oh, I tried to link to the online tests that were failing but I haven't found a way to get back to previous test runs on the same commit.

**Review by aburrell — APPROVED** [review]
Everything passes locally for me, and I can't find any issues.

**Pull request merged**
