### PR TITLE
ENH: Added 'time' back to testing instruments

### PR DESCRIPTION
**Pull request by rstoneback**
# Description

Addresses # (issue)

Restores 'time' back to testing xarray instruments.
Adds DeprecationWarning for 'time'
Fixed concat issue for different index names.

## Type of change

Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Tested locally with pytest

**Test Configuration**:
* MacOS 10.15.4
ant

# Checklist:

- [ ] Make sure you are merging into the ``develop`` (not ``master``) branch
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] Add a note to ``CHANGELOG.md``, summarizing the changes

### CODE REVIEW

**Comment by jklenzing** [comment]
Can we remove the deprecation message to keep commented code to a minimum?

**Comment by rstoneback** [comment]
> Can we remove the deprecation message to keep commented code to a minimum?

I certainly can. I know I'm the only one who likes commented code. That being said, this line is highly likely to return, for either 'Epoch' or 'time', once we get some feedback from the community.

**Comment by jklenzing** [comment]
Fixed the merge issues resulting from new style standards.

**Comment by jklenzing** [comment]
Errors are all flake8 related.  As some of these have been solved in the main icon branch, I recommend merging and sorting out whatever's left there.

**Comment by rstoneback** [comment]
Thanks for the comments. I was just starting to track this down. I'll merge this in then.

**Pull request merged**
