### PR TITLE
BUG: repr for pysat classes, especially Files

### LINKED ISSUE #636: Potential Bug: Instrument `__repr__` and keywords
**Describe the bug**
Underlying instrument keywords, eval, and `__repr__` aren't getting along.

**To Reproduce**

```
import pysat
from pysat import Instrument  

testinst = pysat.Instrument('pysat', 'testing')        

In [21]: eval(testinst.__repr__())                                                                                                                                                                                          
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-21-6438855a7295> in <module>
----> 1 eval(testinst.__repr__())

<string> in <module>

~/Code/pysat/pysat/_instrument.py in __init__(self, platform, name, tag, inst_id, clean_level, update_files, pad, orbit_info, inst_module, multi_file_day, manual_org, directory_format, file_format, temporary_file_list, strict_time_flag, ignore_empty_files, labels, custom, **kwargs)
    425 
    426         if len(missing_keys) > 0:
--> 427             raise ValueError('unknown keyword{:s} supplied: {:}'.format(
    428                 '' if len(missing_keys) == 1 else 's', missing_keys))
    429 

ValueError: unknown keyword supplied: ['load']
```                                                                                                                                                                            
**Expected behavior**
Ideally, `eval(object.__repr__())` should return the original object. Though this can't be true for pysat Instruments in general, it would be nice if it worked for a basic instrument. 

This issue may also indicate a small gap in our updated systems for pysat 3 regarding instrument keywords and surrounding areas that is worth looking into.

**Additional context**

### LINKED ISSUE #667: BUG: files __repr__
**Describe the bug**
Files repr function doesn't work when loading with inst_module instead of platform/name.

**To Reproduce**
```
import datetime as dt
import pysat
import pysatNASA
orbit_info = {'index': 'mlt', 'kind': 'local time'}
ivm = pysat.Instrument(inst_module=pysatNASA.instrument.cnofs_ivm, orbit_info=orbit_info, clean_level='none')
print(ivm.files)
```

Yields (on my system)

```
Local File Statistics
---------------------
Number of files: 927
Date Range: 10 April 2009 --- 01 April 2015
```

Then...

```
ivm.files
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/IPython/core/formatters.py in __call__(self, obj)
    700                 type_pprinters=self.type_printers,
    701                 deferred_pprinters=self.deferred_printers)
--> 702             printer.pretty(obj)
    703             printer.flush()
    704             return stream.getvalue()

/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/IPython/lib/pretty.py in pretty(self, obj)
    392                         if cls is not object \
    393                                 and callable(cls.__dict__.get('__repr__')):
--> 394                             return _repr_pprint(obj, self, cycle)
    395 
    396             return _default_pprint(obj, self, cycle)

/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/IPython/lib/pretty.py in _repr_pprint(obj, p, cycle)
    698     """A pprint that just redirects to the normal repr function."""
    699     # Find newlines and replace them with p.break_()
--> 700     output = repr(obj)
    701     lines = output.splitlines()
    702     with p.group():

~/Programs/Git/pysat/pysat/_files.py in __repr__(self)
    236         """ Representation of the class and its current state
    237         """
--> 238         inst_repr = pysat.Instrument(**self.inst_info).__repr__()
    239 
    240         out_str = "".join(["Files(", inst_repr, ", directory_format=",

~/Programs/Git/pysat/pysat/_instrument.py in __init__(self, platform, name, tag, inst_id, clean_level, update_files, pad, orbit_info, inst_module, directory_format, file_format, temporary_file_list, strict_time_flag, ignore_empty_files, labels, custom, **kwargs)
    230 
    231                 # Look to module for instrument functions and defaults
--> 232                 self._assign_attrs(by_name=True)
    233             elif (platform is None) and (name is None):
    234                 # Creating "empty" Instrument object with this path

~/Programs/Git/pysat/pysat/_instrument.py in _assign_attrs(self, by_name, inst_module)
   1064                 if self.platform not in user_modules.keys():
   1065                     raise KeyError('unknown platform supplied: {:}'.format(
-> 1066                         self.platform))
   1067 
   1068                 if self.name not in user_modules[self.platform].keys():

KeyError: 'unknown platform supplied: cnofs'
```

**Expected behavior**
A representation string that provides the information needed to reproduce the Files object.

**Desktop (please complete the following information):**
 - OS: OS X Mojavve
 - Version: 3.7
 - Other details about your setup that could be relevant: on latest develop-3 branch

### PR DESCRIPTION
**Pull request by aburrell**
# Description

Fixes a bug that occurs when using `inst_module` to load data from an unregistered module and attempting to use `Files.__repr__`. This PR resolves #667.  Will also resolve #636 once PR #670 is incorporated.

This removes the " -> # Things" that used to be on the end of many repr strings, since it doesn't play well with `eval`.  Most (but not all) of the class evals work.  The ones that don't only don't work because the upstream module object reprs don't work (and we can't change that).

I DID NOT add eval unit tests because most objects don't have `__eq__` functions.  Something for the future.

## Type of change

Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Ran unit test locally.  Also for an unregistered module:

```
import pysat
import pysatNASA
orbit_info = {'index': 'mlt', 'kind': 'local time'}
ivm = pysat.Instrument(inst_module=pysatNASA.instruments.cnofs_ivm, orbit_info=orbit_info, clean_level='none')
ivm.files
Files(Instrument(platform='cnofs', name='ivm', inst_id='', clean_level='clean', pad=None, orbit_info={}, custom=[], **{'load': {'file_cadence': datetime.timedelta(days=1), 'flatten_twod': True}, 'list_remote_files': {'remote_url': 'https://cdaweb.gsfc.nasa.gov', 'two_digit_year_break': None, 'delimiter': None}}), directory_format='{platform}/{name}/{tag}/{inst_id}', update_files=True, file_format=None, write_to_disk=True, ignore_empty_files=False)

rfiles = ivm.files.__repr__()
test_files = eval(rfiles)

test_files
Files(Instrument(platform='cnofs', name='ivm', inst_id='', clean_level='clean', pad=None, orbit_info={}, custom=[], **{'load': {'file_cadence': datetime.timedelta(days=1), 'flatten_twod': True}, 'list_remote_files': {'remote_url': 'https://cdaweb.gsfc.nasa.gov', 'two_digit_year_break': None, 'delimiter': None}}), directory_format='{platform}/{name}/{tag}/{inst_id}', update_files=True, file_format=None, write_to_disk=True, ignore_empty_files=False)
```

Your local system should not have identical output to mine :P 

**Test Configuration**:
* Operating system: OS X Mojave
* Version number: 3.7
* Any details about your local setup that are relevant: no registered modules!

# Checklist:

- [x] Make sure you are merging into the ``develop`` (not ``main``) branch
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] Add a note to ``CHANGELOG.md``, summarizing the changes

### CODE REVIEW

**Comment by rstoneback** [comment]
I've confirmed that `ivm.files` does not work with an unregistered instrument unless I use this branch.

**Comment by jklenzing** [comment]
Testing with a registered instrument:
```
import pysat
ivm = pysat.Instrument('cnofs', 'ivm')
ivm.files.inst_info
```
yields
```
{'platform': 'cnofs',
 'name': 'ivm',
 'tag': '',
 'inst_id': '',
 'inst_module': None}
```
Which seems like a mistake.  Ideally, I'd like to see this as the module path, ie, `pysatNASA.instruments.cnofs_ivm`

**Comment by aburrell** [comment]
There's currently no requirement that the new `inst_module` attribute be a recognized module, so this is reflective of the use of a registered instrument.  Since the information is retrievable elsewhere and doesn't add more functionality here I don't think the added time and memory carrying around that link is worth the ease of information access.  Thoughts?

From: Jeff Klenzing <notifications@github.com>


Testing with a registered instrument:

import pysat

ivm = pysat.Instrument('cnofs', 'ivm')

ivm.files.inst_info

yields

{'platform': 'cnofs',

 'name': 'ivm',

 'tag': '',

 'inst_id': '',

 'inst_module': None}

Which seems like a mistake. Ideally, I'd like to see this as the module path, ie, pysatNASA.instruments.cnofs_ivm

**Comment by rstoneback** [comment]
I added inst_info to files to clean up the code a little bit and collect some info needed for the class. Normally I would've kept it hidden but since there have been requests to keep things visible here we are :) 
I don't see a benefit.

**Comment by aburrell** [comment]
Ok... clearly I am not completely on the ball today.  I was accidentally working off of this branch instead of develop.  In any case, the description up top is about to be updated.

**Comment by aburrell** [comment]
Also, https://github.com/pysat/pysatNASA/pull/43 can be tested once this PR is merged.

**Review by jklenzing — COMMENTED** [review]
I'd recommend deleting the files for `test_add_opposite`, `test_add_similar`, `test_diff_same`, and `test_diff_similar`.  The `add` and `diff` functions that these were used to test have been removed, and they're basically now copies of each other since we've pulled out all the extra tags from the test instruments.  We should probably have a 2d xarray constellation object, but that should be a separate pull (and issue), maybe for 3.1.0.

**Review by jklenzing — APPROVED** [review]

**Review by rstoneback — APPROVED** [review]
Thanks @aburrell. Closing the task loop :)

**Comment by jklenzing** [comment]
Answering my own earlier question, the value for `inst.files.inst_info['inst_module']` is what I would expect if I load by the module itself, so I'm happy with the current implementation here.

**Comment by aburrell** [comment]
Now to wait on Travis...

**Comment by jklenzing** [comment]
:sloth:

**Pull request merged**
