### PR TITLE
DOC: Update README.md with badge info

### PR DESCRIPTION
**Pull request by jklenzing**
The badge on the main page is still pointing to the old organization.

### CODE REVIEW

**Comment by aburrell** [comment]
Why is 2.7 failing?

**Comment by jklenzing** [comment]
Seems to be a server issue for the cnofs ivm.  We need to migrate to travis-ci.com to regain the ability to rerun the tests for this without faking changes in the code.  Adding to agenda for next meeting.

**Comment by jklenzing** [comment]
To clarify, it is related to a glitch on the server, not the code.  Usually, when I see this, I can rerun the test to verify.

**Comment by jklenzing** [comment]
Reran the code by adjusting whitespace in the readme.  Server work snow.

**Pull request merged**
