### PR TITLE
Netcdf meta

### PR DESCRIPTION
**Pull request by asher-pembroke**
# Description

Addresses #276 

Added instrument __setattr__ and __getattr__ so that custom instrument attributes get stored as meta attributes. This fixes a problem where instrument attributes were not being updated properly when writing to netcdf.

In other words,
```python
inst.myattr = 'new'
assert inst.myattr == inst.meta.myattr
assert 'myattr' not in dir(inst)
```
Attributes are set/retrieved by the following priority:
1. set (get)  to (from) `inst._base_attr`
2. set (get) to (from) `inst.meta`
3. set (get) to (from) remaining `inst` attributes

I think this approach is more consistent with the goal of having one place to store instrument metadata, but I would like more input on this design change before going further. 

## Type of change

Please delete options that are not relevant.

- Breaking change (see invalidated test below)
- This change requires a documentation update

# How Has This Been Tested?

- New test added to test_utils.py:
 test_netcdf_attribute_override
- This change _invalidates_ the following test within test_meta.py:
test_transfer_attributes_to_instrument_no_meta_attr

More tests to follow if this approach is acceptable 

**Test Configuration**:
* Mac OS X 10.13.6
* python 3.7.3

# Checklist:

- [x] Make sure you are merging into the ``develop`` (not ``master``) branch
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [ ] Add a note to ``CHANGELOG.md``, summarizing the changes

### CODE REVIEW

**Comment by rstoneback** [comment]
The overall feature looks nice. It keeps access across meta and the instrument itself consistent.

The only part I don't really like is having .test_dates written to a file.

**Comment by jklenzing** [comment]
While test_dates aren't particularly useful outside of the testing environment, we should aim for consistency unless there's a good reason not to.  Are these attributes written to operational files?  ie, files to be distributed to the community?

**Comment by rstoneback** [comment]
The tests are failing as the to_netcdf4 routine tries to write the info to files. This will include, say, the ICON IVM files. Yes, it includes community distributed files.

We could switch to a leading _ on test_dates. to_netcdf4 ignores those attributes when writing to a file. Plus, it is consistent with the _ naming of users shouldn't generally mess with it.

**Comment by jklenzing** [comment]
> The tests are failing as the to_netcdf4 routine tries to write the info to files. This will include, say, the ICON IVM files. Yes, it includes community distributed files.
> 
> We could switch to a leading _ on test_dates. to_netcdf4 ignores those attributes when writing to a file. Plus, it is consistent with the _ naming of users shouldn't generally mess with it.

I like switching to to `_test_dates`.  It's an elegant fix, and sets a precedent for future metadata that might be added.

**Comment by rstoneback** [comment]
Great. Asher, please change the test_dates attribute to _test_dates.

Cheers,
Russell

**Comment by asher-pembroke** [comment]
I have changed all appearances of `test_dates` to `_test_dates` and  updated the instrument docs to reflect the change.

**Comment by jklenzing** [comment]
Since we're changing api with the change in `test_date`,  should this be pushed to 3.0?  Adding to agenda.

**Comment by asher-pembroke** [comment]
I don't understand why `pysat/instruments/cosmic_gps.py` still shows as conflicting even though I removed it from my branch. Not sure how to resolve.

**Comment by jklenzing** [comment]
Not sure what's up here.  You should be able to copy over cosmic_gps.py from the latest develop branch and save it here.  I just did a test run to delete a file, commit, restore it, commit.  It shows up as a net-zero change in the final pull requet.

**Comment by rstoneback** [comment]
supplanted by #318

**Pull request merged**
