### PR TITLE
Constellation initialization for registered Instruments

### PR DESCRIPTION
**Pull request by aburrell**
# Description

Partially addresses #795 by adding optional kwargs for initializaing a Constellation by specifying lists of platforms, names, tags, and inst_ids.  Also added documentation for this specific functionality, partially addressing #796.

## Type of change

Please delete options that are not relevant.

- New feature (non-breaking change which adds functionality)
- This change requires a documentation update

# How Has This Been Tested?

Added a new unit test and an example in the docs.  A further example is given below.  Assumes all modules are registered.

```
import pysat

ivm = pysat.Constellation(names=['ivm'])
print(ivm)

pysat Constellation object:
---------------------------
17 Instruments

Index Platform Name Tag Inst_ID
-------------------------------
0 'cnofs' 'ivm' '' ''
1 'formosat1' 'ivm' '' ''
2 'icon' 'ivm' '' 'a'
3 'icon' 'ivm' '' 'b'
4 'dmsp' 'ivm' 'utd' 'f11'
5 'dmsp' 'ivm' '' 'f11'
6 'dmsp' 'ivm' 'utd' 'f12'
7 'dmsp' 'ivm' '' 'f12'
8 'dmsp' 'ivm' 'utd' 'f13'
9 'dmsp' 'ivm' '' 'f13'
10 'dmsp' 'ivm' 'utd' 'f14'
11 'dmsp' 'ivm' '' 'f14'
12 'dmsp' 'ivm' 'utd' 'f15'
13 'dmsp' 'ivm' '' 'f15'
14 'dmsp' 'ivm' '' 'f16'
15 'dmsp' 'ivm' '' 'f17'
16 'dmsp' 'ivm' '' 'f18'


Loaded Data Statistics
----------------------
No loaded data.
```
**Test Configuration**:
* Operating system: OS X Mojave
* Version number: Python 3.9
* Any details about your local setup that are relevant: pysat ecosystem modules are registered.

# Checklist:

- [x] Make sure you are merging into the ``develop`` (not ``main``) branch
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] Add a note to ``CHANGELOG.md``, summarizing the changes

If this is a release PR, replace the first item of the above checklist with the release
checklist on the wiki: https://github.com/pysat/pysat/wiki/Checklist-for-Release

### CODE REVIEW

**Review by rstoneback — COMMENTED** [review]
Thanks @aburrell! I tried your example, plus a few variants and it worked well. Downloaded some 'realtime' data, etc.

I tried putting in some nonsense values for platform, etc. The code ran fine but didn't let me know that some inputs were nonsense. 
```
In [18]:  ^I  import pysat 
    ...:  ^I  import pysatSpaceWeather 
    ...:  ^I  # If you haven't registered this module before, do it now 
    ...:  ^I  pysat.utils.registry.register_by_module(pysatSpaceWeather.instruments) 
    ...:  ^I  # Now initialize the ACE real-time Constellation 
    ...:  ^I  ace_rt = pysat.Constellation(platforms=['ace', 'momma'], names=['epam', 'mag', 'coming'], tags=['realtime', 'home']) 
    ...:  ^I  # Display the results 
    ...:  ^I  print(ace_rt)                                                                                                                                                                                                   
pysat Constellation object:
---------------------------
2 Instruments

Index Platform Name Tag Inst_ID
-------------------------------
0 'ace' 'epam' 'realtime' ''
1 'ace' 'mag' 'realtime' ''


Loaded Data Statistics
----------------------
No loaded data.
```

I also turned on the logger to check there. There was a whole bunch of debug an info statements from the Instrument instantiation, which makes sense. Given that though, perhaps a Warning, or maybe an Error, could be appropriate if inputs aren't recognized.

**Review by rstoneback — COMMENTED** [review]
Thanks @aburrell. The changes look good to me. While reviewing this I did think of something new. It is possible some users could want a more strict instantiation check that produces an error if any inputs aren't recognized, while others would prefer the more relaxed version here. Depending on the situation some users may want different behavior. What If we made the strictness of this check a user option in pysat.params? Label it something like `Error_Some_Unsupported_Instruments_in_Constellation`....  and have the default be the current behavior.

**Comment by aburrell** [comment]
That's a good idea, and will also affect the other init methods.  Definitely should be an issue!

**Comment by rstoneback** [comment]
https://github.com/pysat/pysat/issues/832

**Review by rstoneback — APPROVED** [review]

**Pull request merged**
