### PR TITLE
TST: Update Travis CI environment

### PR DESCRIPTION
**Pull request by jklenzing**
# Description

Addresses #383 

This is a fix for recent changes in the Travis CI environment.  See #382 for more discussion.

## Type of change

- Bug fix - testing environment (non-breaking change which fixes an issue)

# How Has This Been Tested?

via Travis CI

# Checklist:

- [x] Make sure you are merging into the ``develop`` (not ``master``) branch
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] Add a note to ``CHANGELOG.md``, summarizing the changes

### CODE REVIEW

**Comment by jklenzing** [comment]
The alternative to this is to impose a limit in setup.  It is unknown whether this affects distributions outside of Travis CI, though presumably it would affect some linux systems.

**Comment by rstoneback** [comment]
Thanks Jeff and Angeline. Should the version limit be placed within setup.py to help ensure things work out of the box for linux folks? We have limits on most things already, why not go all the way? Could be very helpful to someone who comes along in 5 years or perhaps even a few months.

Incidentally, the links you included to the netCDF issue now show up within that issue. For some reason I didn't know that worked across projects/groups. They know that we are talking netCDF :)

**Comment by jklenzing** [comment]
I'm open to either, as long as we document why the restriction is in place so that we can hopefully lift it in the future.  @aburrell?

**Comment by aburrell** [comment]
Well, I know it's easier for new users to not have restrictions so that they can more easily install all the different packages they need.  If this restriction is only needed for a subset of operating systems, I think that should be documented and a restriction not used.  If it's needed for all operating systems, then I agree with @jklenzing.

**Comment by jklenzing** [comment]
I'll go ahead and document one other thing:  It is not clear to me what exactly what caused this bug to appear last week.  I've been digging through the Travis logs for the develop branches, and I do not see any changes in software versions.  It could be a change in memory allocation on virtual machines or something else outside of view.  

Until we have more info, I say we merge this in and monitor the situation.

**Pull request merged**
