### PR TITLE
DOC/TST: deprecation in docstring, format stuff, test compliance

### PR DESCRIPTION
**Pull request by jklenzing**
# Description

- Adds deprecation info to docstrings according to numpydoc
- minor formatting issues.
- Fixes a test that required pytest

## Type of change

- This change is a documentation update

# How Has This Been Tested?

make html

# Checklist:

- [x] Make sure you are merging into the ``develop`` (not ``master``) branch
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [ ] Add a note to ``CHANGELOG.md``, summarizing the changes

### CODE REVIEW

**Comment by jklenzing** [comment]
Double checked the changelog to make sure deprecation history is correct, used a global search deprecationwarning to find where docstrings need to be updated.

**Comment by jklenzing** [comment]
@rstoneback, the updated test is here

**Comment by rstoneback** [comment]
Awesome. Fingers crossed :)

On Jul 24, 2020, at 5:57 PM, Jeff Klenzing <notifications@github.com> wrote:

﻿

@rstoneback<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Frstoneback&data=02%7C01%7Crstoneba%40utdallas.edu%7C018215e3c56241b210e808d83024e8c9%7C8d281d1d9c4d4bf7b16e032d15de9f6c%7C0%7C0%7C637312282378043377&sdata=MQHe4Vz6ycQ5vFrGUzph2gPn4QzfkOjinXwH%2FfNAq%2F0%3D&reserved=0>, the updated test is here

**Comment by jklenzing** [comment]
turn out it doesn't like python 3.  fixing...

**Comment by rstoneback** [comment]
> turn out it doesn't like python 3. fixing...

Of course. That one is on me.

**Comment by jklenzing** [comment]
@rstoneback, would `str(execinfo)` work in python 2.7?  this works for 3.

**Comment by jklenzing** [comment]
virtual env set up.  looks like it does

**Comment by rstoneback** [comment]
@jklenzing That works.

**Comment by jklenzing** [comment]
Found one more tiny thing: dmsp and jro should use the general methods, not cdw.

**Pull request merged**
