### PR TITLE
ENH: Expanded data date range loading options

### PR DESCRIPTION
**Pull request by rstoneback**
# Description

Addresses #58 

pysat began with the assumption of loading a single day of data. This pull relaxes that assumption to support loading arbitrary timespans. This changes the `inst.load` method signature but shouldn't break any existing code.

Loading a range of dates, using that range of dates under iteration, and via next/prev is supported.

Data padding and the multi_file_day option likely don't work yet, haven't started on those areas yet.

## Type of change

Please delete options that are not relevant.

- New feature (non-breaking change which adds functionality)
- This change requires a documentation update

# How Has This Been Tested?

TravisCI and local sampling

# Checklist:

- [x] Make sure you are merging into the ``develop`` (not ``main``) branch
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] Add a note to ``CHANGELOG.md``, summarizing the changes

### CODE REVIEW

**Comment by rstoneback** [comment]
```
In [11]: inst = pysat.Instrument('pysat', 'testing')                                                                                                               
In [12]: inst.load(2009,1)                                                                                                                                                                             
In [14]: print(inst)                                                                                                                                                                                   
Loaded Data Statistics
----------------------
Date: 01 January 2009
DOY: 001
Time range: 01 January 2009 00:00:00 --- 01 January 2009 23:59:59
Number of Times: 86400
Number of variables: 17

See variable names using print(inst.variables)

```

Currently follows slicing syntax, first date is inclusive, second date is exclusive. Date selection is applied at file level.
```
In [15]: inst.load(2009, 1, 2009, 3)                                                                                                                                                                   

In [16]: print(inst)                                                                                                                                                                                   

Loaded Data Statistics
----------------------
Date: 01 January 2009
DOY: 001
Time range: 01 January 2009 00:00:00 --- 02 January 2009 23:59:59
Number of Times: 172800
Number of variables: 17

```

Next(), using the relative increment obtained from user dates.
```
In [17]: inst.next()                                                                                                                                                                                   

In [18]: print(inst)                                                                                                                                                                                   

Loaded Data Statistics
----------------------
Date: 03 January 2009
DOY: 003
Time range: 03 January 2009 00:00:00 --- 04 January 2009 23:59:59
Number of Times: 172800
Number of variables: 17
```

**Comment by rstoneback** [comment]
pinging @aburrell given previously stated interest in this particular feature plus I'd appreciate early feedback on the standards picked so far.

**Comment by rstoneback** [comment]
Issues to be resolved:
 [ ] Data Padding
 [ ] multi-file-day check
 [ ] what happens to inst.date? Add or replace inst.dates?
 [ ] To Be Determined

**Comment by rstoneback** [comment]
I also removed fid as an input option for `inst.load`. It is redundant with the `fname` keyword since
`inst.load(fid=n)` could also be `inst.load(fname=inst.files[n])`. I'd have to go back to v2.2.x and add some deprecation warnings. I haven't cleared out the tests or anything like that yet. Majority of test failures are driven by lack of fid.

The next() and prev() methods are currently having some trouble when loading by filename. Iteration methods are driven by `inst.bounds`, which defaults to iteration by date. I currently have a bit of a conflict between `inst.bounds` and setting the data loading window via `inst.load()` calls. There are a couple test failures related to this. Adding to working checkbox list.

**Comment by rstoneback** [comment]
There is an inconsistency between `bounds` and `load` because I made one. Proposal to remove:
 - `bounds` updated to accept, up to, [start_dates, end_dates, step_size, load_window_size]
 - rename `inst.increment` to something like `inst.load_incr` or `inst.load_step`
 - add attributes, `inst.bounds_step` and `inst.bounds_window`

**Comment by rstoneback** [comment]
> There is an inconsistency between `bounds` and `load` because I made one. Proposal to remove:
> 
> * `bounds` updated to accept, up to, [start_dates, end_dates, step_size, load_window_size]
> * rename `inst.increment` to something like `inst.load_incr` or `inst.load_step`
> * add attributes, `inst.bounds_step` and `inst.bounds_window`

The inconsistency has been resolved. `inst.bounds` relates to iteration, and loading options apply to loading. 

Code before any changes here allows users to load data outside the ranges listed by `.bounds`. Thus the current standard is bounds is not coupled to load, and vice versa.

**Comment by rstoneback** [comment]
inst.bounds currently works with more than one kind of input. Wasn't expecting this.

```
In [6]: inst.bounds = [dt.datetime(2009, 1, 1), dt.datetime(2009, 1, 10), pds.DateOffset(days=2), pds.DateOffset(days=3)]                                                                              

In [7]: for inst in inst: 
   ...:     print(inst.index[0], ' ---- ', inst.index[-1]) 
   ...:                                                                                                                                                                                                
2009-01-01 00:00:00  ----  2009-01-03 23:59:59
2009-01-03 00:00:00  ----  2009-01-05 23:59:59
2009-01-05 00:00:00  ----  2009-01-07 23:59:59
2009-01-07 00:00:00  ----  2009-01-09 23:59:59
2009-01-09 00:00:00  ----  2009-01-11 23:59:59

In [8]: inst.bounds = [dt.datetime(2009, 1, 1), dt.datetime(2009, 1, 10), '2D', pds.DateOffset(days=3)]                                                                                                

In [9]: for inst in inst: 
   ...:     print(inst.index[0], ' ---- ', inst.index[-1]) 
   ...:                                                                                                                                                                                                
2009-01-01 00:00:00  ----  2009-01-03 23:59:59
2009-01-03 00:00:00  ----  2009-01-05 23:59:59
2009-01-05 00:00:00  ----  2009-01-07 23:59:59
2009-01-07 00:00:00  ----  2009-01-09 23:59:59
2009-01-09 00:00:00  ----  2009-01-11 23:59:59
```

**Comment by rstoneback** [comment]
@aburrell and @jklenzing 

I believe all the functionality required for loading range of dates working in this pull. I have a notebook up at pysat/pysatTutorials/#2 with a demo of the changes. I'd greatly appreciate a mini-review of how things work and feel. If something needs to change easier to do earlier than later. No worries though. In the meantime, I'm going to continue to expand the unit tests, verify style, comments, etc. Should be ready for full review early next week.

**Comment by aburrell** [comment]
I checked out this branch and did a quick look at the tutorial examples.  It works on the test instruments, but not on CINDI.  And it seems like it should, because the files are there and the load function has all the right keywords.  I suppose they aren't being passed to the local instrument?

Also, not a huge fan of `date`, `date2`.  I'd have expected the same keywords as the download function.

Finally, I'd recommend using a 3 day range in the tutorial, to show that it will span the times/files in between the start and stop but still not take very long.

**Comment by rstoneback** [comment]
> I checked out this branch and did a quick look at the tutorial examples. It works on the test instruments, but not on CINDI. And it seems like it should, because the files are there and the load function has all the right keywords. I suppose they aren't being passed to the local instrument?

My first guess is CINDI is probably just looking at a single filename. Instruments will work without modification if they are fully pysat compliant. Multiple filename support wasn't a priority for datasets that are in daily chunks so there are likely a few instrument support modules that will require updating.

> 
> Also, not a huge fan of `date`, `date2`. I'd have expected the same keywords as the download function.

OK. I can update them. date2 is bad. date was already there so I was keeping it for maximum compatibility.
We can fully go to something like `start_date` and `stop_date` but any current code that uses `date` or `fname` will break. My current thinking is something like, `date` and `end_date`, `fname` and `last_fname`. I have some proposals to work on today but I'll give it some thought.


> 
> Finally, I'd recommend using a 3 day range in the tutorial, to show that it will span the times/files in between the start and stop but still not take very long.

Thanks!

**Comment by rstoneback** [comment]
Closing now due to length of comment history. Will reopen a new, clean pull, when ready.

**Pull request closed without merging**
