### PR TITLE
BUG/ENH: Cosmic bug and scintillation data -- pysat 3.0.0

### PR DESCRIPTION
**Pull request by jklenzing**
# Description

Addresses #312.  pysat 3.0.0 version of #313. Includes related updates from #305.

## Type of change

Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

See #313.

# Checklist:

- [x] Make sure you are merging into the ``develop`` (not ``master``) branch
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] Add a note to ``CHANGELOG.md``, summarizing the changes

### CODE REVIEW

**Comment by rstoneback** [comment]
I think this got pulled in with the asher meta pull

**Comment by jklenzing** [comment]
This is the twin of that pull. I thought at the last meeting we were to set up pull request into both develop branches. It might be easier just to merge from develop now. @aburrell, how should we do this?

**Comment by aburrell** [comment]
I think twins are the way to go.  We can mark it as a twin in the description and refer back to the PR with the review comments.  Then, the review can focus on the areas that need conflict resolution.

**Comment by jklenzing** [comment]
Ok. Flags are above. The conflicts are more complicated than I can fix on my phone, so I’ll tidy that up next week for the review.

**Comment by jklenzing** [comment]
Superseded by #325.

**Pull request closed without merging**
