### PR TITLE
DOC: v22 update

### PR DESCRIPTION
**Pull request by rstoneback**
# Description

Addresses #464 

Documentation is getting a review and update.

## Type of change

Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

# Checklist:

- [x] Make sure you are merging into the ``develop`` (not ``master``) branch
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] Add a note to ``CHANGELOG.md``, summarizing the changes

### CODE REVIEW

**Comment by rstoneback** [comment]
@jklenzing can you take a look at the testing info in new_instruments.rst ?

**Comment by rstoneback** [comment]
@jklenzing can you also take a look at the general instrument template to make sure it has all the testing flags and other info for v2.2?

**Comment by rstoneback** [comment]
@jklenzing and @aburrell if either of you know of an area of the documentation that isn't so hot please let me know. I'm going to continue to take my own pass through but it is likely I don't read it in the same way ... too close.

**Comment by aburrell** [comment]
Read through "Introduction, Installation, and Tutorial":

- Set Data Directory belongs in a Quick-Start section rather than Installation
- Does python remind you if the data directory isn't set?  Also, a reminder of how to find this directory by asking the user to print it out in the example would be good
- A link to the pysatCDF library page should be provided.
- Before "Instantiation", tell user how to discover the different possible platforms, instruments, tags, and sat_ids.
- In "Instantiation", just use one instrument as an example.  Picking an example that uses all the options would be best.
- Bug in download display
- Load data explains things in a way that is no longer strictly accurate.
- For the example that requires a CDAAC account, provide a link sending the user there
- Recommend breaking the tutorial up into different files, so having a tutorial directory with each section as its own file.  The main tutorial could be an index, allowing the user to see everything in smaller, more manageable sections
- Do a better job differentiating between 'add' and 'modify' for custom functions, I still don't understand this and I think I was the last one to touch this section of the docs.
- Have a description of the header before the example code (e.g., Adding Instrument Independence).
- Remove "pending" sections and put in an issue instead.
- Grammar: "The seasonal analysis loop is repeated commonly"
- Orbital support: make a note on how this is treated for instruments that do not have orbits
- Move verbosity up to be right after basics

**Comment by jklenzing** [comment]
> @jklenzing can you also take a look at the general instrument template to make sure it has all the testing flags and other info for v2.2?

This should be good.  The testing flags are only used in v3.0.  I think I left these in the 2.2 release files for ICON.  It's harmless, but I could clean that up to prevent confusion.

**Comment by rstoneback** [comment]
I think it’s fine for ICON. 

Thanks for verifying the example file is current regarding testing.

**Comment by jklenzing** [comment]
Installation
- [ ] anaconda link not formatted in build
- [ ] perhaps point people to use pip install netCDF4
Tutorial
- [ ] There's no real discussion of what metadata pysat stores, only how to access it
Adding a New Instrument
- [ ] pysat now has a standardized list_files rouinte under general methods.  It would be good to point developers there
- [ ] rather than repeat autodoc info for nasa/madrigal methods here, just link to the appropriate part of supported_instruments

When building locally, I get 64 warnings, mostly autdoc related.  I also notice that some of the formatting from autodoc can be updated.  I can take a pass at both of these in a downstream pull.

**Comment by rstoneback** [comment]
pysat must know a release is coming. I'm having trouble with all the download methods of late. 

I can't get Madrigal downloads going to verify my statements in the documentation ... 
I can't get Madrigal to work directly on the website either so, blah!

Perhaps a blanket statement in the downloads section that science data servers aren't very reliable is appropriate :)

**Comment by aburrell** [comment]
The "Contributing" subheadings show up in the main index, and they shouldn't.

**Comment by rstoneback** [comment]
Thanks for the note. I pushed my accumulated commits since you are poking at it.

**Comment by aburrell** [comment]
There's a visible "<br>" in the FAQ.  Also recommend moving citations up to follow the introduction.  Finally, maybe rename "code examples" "sample analysis"?

**Comment by rstoneback** [comment]
> The "Contributing" subheadings show up in the main index, and they shouldn't.

How should it show up?

**Comment by aburrell** [comment]
As sub-indexes.  Check out: https://ocbpy.readthedocs.io/en/vec_docs/citing.html#

**Comment by rstoneback** [comment]
> 
> Adding a New Instrument
> 
> * [ ]  pysat now has a standardized list_files rouinte under general methods.  It would be good to point developers there
> * [ ]  rather than repeat autodoc info for nasa/madrigal methods here, just link to the appropriate part of supported_instruments

hey @jklenzing  - are these still active for me or did you include this in one of your many commits?

**Comment by rstoneback** [comment]
@aburrell and @jklenzing I've accounted for all comments and ready for a re-review when you have a chance.

**Comment by aburrell** [comment]
This is loads better.  Bring in Jeff's pulls and let's get this out.

**Comment by rstoneback** [comment]
Awesome. Will do. I'll go click a series of buttons! :)

**Pull request merged**
