### PR TITLE
BUG: Bad bounds date extraction

### PR DESCRIPTION
**Pull request by rstoneback**
# Description

Addresses # (issue)

The files object is responsible for setting a pysat.Instrument objects date bounds. The code grabbed the first and last file from an unsorted list. I now use the list attached to the Files object.

## Type of change

Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?
Travis and local tests.

# Checklist:

- [x] Make sure you are merging into the ``develop`` (not ``master``) branch
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] Add a note to ``CHANGELOG.md``, summarizing the changes

### CODE REVIEW

**Comment by jklenzing** [comment]
Hmm.  Push fails on cnofs_ivm, pull fails on omni.  Trying a re-run of this.

**Comment by jklenzing** [comment]
Upon rerun (documentation changes only): pull times out during dmsp download for 2.7, push times out for the same for 3.7.  I'm calling server issues.

**Comment by jklenzing** [comment]
Servers passing now.

**Comment by rstoneback** [comment]
Thanks Jeff!

On Dec 10, 2019, at 11:28 AM, Jeff Klenzing <notifications@github.com> wrote:

﻿

Merged #329<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpysat%2Fpysat%2Fpull%2F329&data=02%7C01%7Crstoneba%40utdallas.edu%7C24dfeaf7494c4586369708d77d966b39%7C8d281d1d9c4d4bf7b16e032d15de9f6c%7C0%7C0%7C637115957343924145&sdata=GQsUy4ZwKWKrXcy8HaYoaU7p2XilqVPd5PT3agI7tjo%3D&reserved=0> into develop.

**Pull request merged**
